
export const REDUCER_OPERATIONS={
LOAD_USERS_LOADING : 'REDUX_SAGA_LOAD_USERS_LOADING',
//token generate on giving username,pwd for /authenticate post api
 LOAD_AUTHENTICATE_TOKEN_REQUEST:'LOAD_AUTHENTICATE_TOKEN_REQUEST',
 LOAD_AUTHENTICATE_TOKEN_SUCCESS:'LOAD_AUTHENTICATE_TOKEN_SUCCESS',
 //on customer registration request--/userRequest post api
 LOAD_USER_REGISTER_REQUEST:'LOAD_USER_REGISTER_REQUEST',
 LOAD_USER_REGISTER_SUCCESS:'LOAD_USER_REGISTER_SUCCESS',

 LOAD_ADMIN_REGISTER_REQUEST:'LOAD_ADMIN_REGISTER_REQUEST',
 LOAD_ADMIN_REGISTER_SUCCESS:'LOAD_ADMIN_REGISTER_SUCCESS',
 LOAD_APPROVE_USER_REQUEST:'LOAD_APPROVE_USER_REQUEST',
 LOAD_APPROVE_USER_SUCCESS:'LOAD_APPROVE_USER_SUCCESS',

 LOAD_USER_BY_NAME_REQUEST:'LOAD_USER_BY_NAME_REQUEST',
 LOAD_USER_BY_NAME_SUCCESS:'LOAD_USER_BY_NAME_SUCCESS',

 LOAD_ALL_BOOKS_DETAILS_REQUEST:'LOAD_ALL_BOOK_DETAILS_REQUEST',
 LOAD_ALL_BOOKS_DETAILS_SUCCESS:'LOAD_ALL_BOOK_DETAILS_SUCCESS',
 LOAD_ALL_USERS_DETAILS_REQUEST:'LOAD_ALL_USERS_DETAILS_REQUEST',
 LOAD_ALL_USERS_DETAILS_SUCCESS:'LOAD_ALL_USERS_DETAILS_SUCCESS',
 LOAD_ADD_BOOK_REQUEST:'LOAD_ADD_BOOK_REQUEST',
 LOAD_ADD_BOOK_SUCCESS:'LOAD_ADD_BOOK_SUCCESS',
 LOAD_ADD_CATEGORY_REQUEST:'LOAD_ADD_CATEGORY_REQUEST',
 LOAD_ADD_CATEGORY_SUCCESS:'LOAD_ADD_CATEGORY_SUCCESS',

//CVView
LOAD_CATEGORYAGE_REQUEST:'LOAD_CATEGORYAGE_REQUEST',
LOAD_CATEGORYAGE_SUCCESS:'LOAD_CATEGORYAGE_SUCCESS',

LOAD_ISSUE_BOOK_REQUEST:'LOAD_ISSUE_BOOK_REQUEST',
LOAD_ISSUE_BOOK_SUCCESS:'LOAD_ISSUE_BOOK_SUCCESS',

LOAD_GET_ALLBOOK_ISSUES_REQUEST:'LOAD_GET_ALLBOOK_ISSUES_REQUEST',
LOAD_GET_ALLBOOK_ISSUES_SUCCESS:'LOAD_GET_ALLBOOK_ISSUES_SUCCESS',

LOAD_ADD_RESPONSE_REQUEST:'LOAD_ADD_RESPONSE_REQUEST',
LOAD_ADD_RESPONSE_SUCCESS:'LOAD_ADD_RESPONSE_SUCCESS',

LOAD_GET_APPROVEDBOOKS_REQUEST:'LOAD_GET_APPROVEDBOOKS_REQUEST',
LOAD_GET_APPROVEDBOOKS_SUCCESS:'LOAD_GET_APPROVEDBOOKS_SUCCESS',

LOAD_RETURN_BOOK_REQUEST:'LOAD_RETURN_BOOK_REQUEST',
LOAD_RETURN_BOOK_SUCCESS:'LOAD_RETURN_BOOK_SUCCESS',

LOAD_GET_OVERDUE_REQUEST:'LOAD_GET_OVERDUE_REQUEST',
LOAD_GET_OVERDUE_SUCCESS:'LOAD_GET_OVERDUE_SUCCESS',

LOAD_CATEGORY_REQUEST:'LOAD_CATEGORY_REQUEST',
LOAD_CATEGORY_SUCCESS:'LOAD_CATEGORY_SUCCESS',

LOAD_DELETE_CATEGORY_REQUEST:'LOAD_DELETE_CATEGORY_REQUEST',
LOAD_DELETE_CATEGORY_SUCCESS:'LOAD_DELETE_CATEGORY_SUCCESS',

LOAD_DELETE_BOOK_REQUEST:'LOAD_DELETE_BOOK_REQUEST',
LOAD_DELETE_BOOK_SUCCESS:'LOAD_DELETE_BOOK_SUCCESS',

LOAD_CUSTOMER_SEARCHFILTER_REQUEST:'LOAD_CUSTOMER_SEARCHFILTER_REQUEST',
LOAD_ADMIN_SEARCHFILTER_REQUEST:'LOAD_ADMIN_SEARCHFILTER_REQUEST',
 LOAD_USERS_ERROR : 'REDUX_SAGA_LOAD_USERS_ERROR',
}