
export const REDUCER_OPERATIONS={
LOAD_USERS_LOADING : 'REDUX_SAGA_LOAD_USERS_LOADING',
//token generate on giving username,pwd for /authenticate post api
 LOAD_AUTHENTICATE_TOKEN_REQUEST:'LOAD_AUTHENTICATE_TOKEN_REQUEST',
 LOAD_AUTHENTICATE_TOKEN_SUCCESS:'LOAD_AUTHENTICATE_TOKEN_SUCCESS',
 //on customer registration request--/userRequest post api
 LOAD_USER_REGISTER_REQUEST:'LOAD_USER_REGISTER_REQUEST',
 LOAD_USER_REGISTER_SUCCESS:'LOAD_USER_REGISTER_SUCCESS',

 LOAD_USER_BY_NAME_REQUEST:'LOAD_USER_BY_ID_REQUEST',
 LOAD_USER_BY_NAME_SUCCESS:'LOAD_USER_BY_ID_SUCCESS',

 LOAD_ALL_BOOKS_DETAILS_REQUEST:'LOAD_ALL_BOOK_DETAILS_REQUEST',
 LOAD_ALL_BOOKS_DETAILS_SUCCESS:'LOAD_ALL_BOOK_DETAILS_REQUEST',
 LOAD_ALL_USERS_DETAILS_REQUEST:'LOAD_MANAGE_CUSTOMERS_DETAILS_REQUEST',
 LOAD_ALL_USERS_DETAILS_SUCCESS:'LOAD_MANAGE_CUSTOMERS_DETAILS_SUCCESS',
 LOAD_ADD_BOOK_REQUEST:'LOAD_ADD_BOOK_REQUEST',
 LOAD_ADD_BOOK_SUCCESS:'LOAD_ADD_BOOK_SUCCESS',
 LOAD_ADD_CATEGORY_REQUEST:'LOAD_ADD_CATEGORY_REQUEST',
 LOAD_ADD_CATEGORY_SUCCESS:'LOAD_ADD_CATEGORY_SUCCESS',

 CUSTOMER_ISSUE_REQUESTS:'CUSTOMER_ISSUE_REQUESTS',


 DELETE_BOOK:'DELETE_BOOK',
 APPROVE_CUSTOMER_REGISTRATION:'APPROVE_CUSTOMER-REGISTRATION',
 APPROVE_CUSTOMER:'APPROVE_CUSTOMER',


 LOAD_USERS_ERROR : 'REDUX_SAGA_LOAD_USERS_ERROR',
}